trigger:
- main
- releases/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Main
  jobs:
  - job: YamlCheck
    steps:
    - script: sudo apt update && sudo apt install -y yamllint curl
      name: InstallDeps

    - script: yamllint $(find $PWD -regex '.*\.yml')
      name: CheckSyntax

    - script: curl -X POST -H 'Content-type: application/json' --data '{"text":"YAML Lint failed"}' $(SLACK_WEBHOOK_URL)
      condition: failed()
      name: AlertOnFailure